### ISSUE TITLE
Problem with dynamic page loading

### ISSUE THREAD

**Issue by danheywood** [geosigno/simpleParallaxJS#30]
Hi, I really like this library but I've ran into an issue where it works perfectly on the initial load, but when I move between from one page, to the next and back again, the animations aren't working. 

I'm using [Barba.js](https://barba.js.org/docs/v2/user/) for the dynamic page loading, but what I am finding is that everything is running as it should, transform, transition and will-change all get added to the element, but when I scroll nothing happens. 

I don't think this is an issue with Barba for this reason. I wonder if you have any idea what could be stopping the animation?

**Comment by geosigno** [comment]
Hi,

It is not easy to shoot in the dark...  any chance to get a demo link so I can take a look at the issue?

Thanks.

**Comment by geosigno** [comment]
I close this issue for now, feel free to re-open if i you can share your code.
