### ISSUE TITLE
Not working with jquery lazyload

### ISSUE THREAD

**Issue by yrogovich** [geosigno/simpleParallaxJS#31]
I am using jQuery lazy plugin for delayed loading of images. But the parallax effect doesn't work with it. How can I delay uploading images?

**Comment by geosigno** [comment]
It should work... can you provide me an example? 
The best approach would be to initialize the simpleParallax in the callback of the lazy load, once the image has been loaded.

**Comment by geosigno** [comment]
I close this issue for now, feel free to re-open if i you can share your code.
