### ISSUE TITLE
Not working in MS Edge

### ISSUE THREAD

**Issue by yonkov** [geosigno/simpleParallaxJS#37]
The parallax effect is working on Firefox and Chrome. However, it is not working in MS Edge. When opening my [website](https://facesandfeelings.com/) with MS Edge, I get the following error:
![image](https://user-images.githubusercontent.com/26258032/72475095-e01f9180-37f2-11ea-8d61-5c7aa8eea33d.png)

The code that I am using to run the parallax is the following:
```
jQuery(function($){
    //Add paralax to home page featured image
    var image = document.querySelectorAll('.attachment-post-thumbnail');
    new simpleParallax(image, {
	    scale: 1.5
    });
});
```

**Comment by lachieh** [comment]
This is an IE11 error, not Edge, and it's happening because IE11 doesn't support the 'closest' method. You will need to use a polyfill to add this functionality.

**Comment by geosigno** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
